#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

RUN_TAG="$(date +%Y%m%d_%H%M%S)"
OUT_DIR_DEFAULT="$ROOT_DIR/logs/auto-aim/$RUN_TAG"
OUT_DIR="${AUTO_AIM_OUT_DIR:-$OUT_DIR_DEFAULT}"

MIN_DISTANCE_M="${AUTO_AIM_MIN_DISTANCE_M:-4.0}"
MIN_MOVING_FEED_SAMPLES="${AUTO_AIM_MIN_MOVING_FEED_SAMPLES:-10}"
MIN_MOVING_FEED_FRACTION="${AUTO_AIM_MIN_MOVING_FEED_FRACTION:-0.65}"
P90_LIMIT_DEG="${AUTO_AIM_ASSERT_P90_DEG:-11.0}"
MAX_LIMIT_DEG="${AUTO_AIM_ASSERT_MAX_DEG:-18.0}"
MIN_DESCENT_SAMPLES="${AUTO_AIM_MIN_DESCENT_SAMPLES:-15}"
IDEAL_DESCENT_MISS_METERS="${AUTO_AIM_IDEAL_DESCENT_MISS_METERS:-0.1524}"
DESCENT_P90_LIMIT_METERS="${AUTO_AIM_ASSERT_DESCENT_P90_METERS:-0.23}"
DESCENT_MAX_LIMIT_METERS="${AUTO_AIM_ASSERT_DESCENT_MAX_METERS:-0.24}"
MIN_DESCENT_WITHIN_IDEAL_FRACTION="${AUTO_AIM_ASSERT_MIN_DESCENT_WITHIN_IDEAL_FRACTION:-0.65}"
POST_AUTO_OBSERVATION_SEC="${AUTO_AIM_POST_AUTO_OBSERVATION_SEC:-3.0}"
SHOOTER_SIM_MOTION_COMP_TIME_SCALE="${SHOOTER_SIM_MOTION_COMP_TIME_SCALE:-}"
SHOOTER_SIM_MOTION_COMP_DISTANCE_TIME_SCALE="${SHOOTER_SIM_MOTION_COMP_DISTANCE_TIME_SCALE:-}"
AUTO_AIM_AUTO_NAME="${AUTO_AIM_AUTO_NAME:-Along Alliance Moving Shot}"

mkdir -p "$OUT_DIR"

echo "Running auto-aim sim diagnostics"
echo "Auto name: $AUTO_AIM_AUTO_NAME"
echo "Output directory: $OUT_DIR"
echo "Thresholds: minDistance=${MIN_DISTANCE_M}m minMovingFeedSamples=${MIN_MOVING_FEED_SAMPLES} minMovingFeedFraction=${MIN_MOVING_FEED_FRACTION} p90Aim<=${P90_LIMIT_DEG}deg maxAim<=${MAX_LIMIT_DEG}deg minDescentSamples=${MIN_DESCENT_SAMPLES} p90DescentMiss<=${DESCENT_P90_LIMIT_METERS}m maxDescentMiss<=${DESCENT_MAX_LIMIT_METERS}m minDescentWithinIdealFraction>=${MIN_DESCENT_WITHIN_IDEAL_FRACTION} idealMiss=${IDEAL_DESCENT_MISS_METERS}m postAutoObserve=${POST_AUTO_OBSERVATION_SEC}s motionCompTimeScale=${SHOOTER_SIM_MOTION_COMP_TIME_SCALE:-<code-default>} motionCompDistanceTimeScale=${SHOOTER_SIM_MOTION_COMP_DISTANCE_TIME_SCALE:-<code-default>}"

GRADLE_EXIT=0
GRADLE_ARGS=(test --tests frc.robot.autos.AlongAllianceMovingShotAutoSimTest)
if [[ -n "$SHOOTER_SIM_MOTION_COMP_TIME_SCALE" ]]; then
  GRADLE_ARGS+=("-Dshooter.sim.motionCompTimeScale=$SHOOTER_SIM_MOTION_COMP_TIME_SCALE")
fi
if [[ -n "$SHOOTER_SIM_MOTION_COMP_DISTANCE_TIME_SCALE" ]]; then
  GRADLE_ARGS+=("-Dshooter.sim.motionCompDistanceTimeScale=$SHOOTER_SIM_MOTION_COMP_DISTANCE_TIME_SCALE")
fi

AUTO_AIM_DIAG_OUT_DIR="$OUT_DIR" \
AUTO_AIM_DIAG_MIN_DISTANCE_METERS="$MIN_DISTANCE_M" \
AUTO_AIM_DIAG_MIN_MOVING_FEED_SAMPLES="$MIN_MOVING_FEED_SAMPLES" \
AUTO_AIM_DIAG_MIN_MOVING_FEED_FRACTION="$MIN_MOVING_FEED_FRACTION" \
AUTO_AIM_DIAG_ASSERT_P90_DEG="$P90_LIMIT_DEG" \
AUTO_AIM_DIAG_ASSERT_MAX_DEG="$MAX_LIMIT_DEG" \
AUTO_AIM_DIAG_MIN_DESCENT_SAMPLES="$MIN_DESCENT_SAMPLES" \
AUTO_AIM_DIAG_IDEAL_DESCENT_MISS_METERS="$IDEAL_DESCENT_MISS_METERS" \
AUTO_AIM_DIAG_ASSERT_DESCENT_P90_METERS="$DESCENT_P90_LIMIT_METERS" \
AUTO_AIM_DIAG_ASSERT_DESCENT_MAX_METERS="$DESCENT_MAX_LIMIT_METERS" \
AUTO_AIM_DIAG_ASSERT_MIN_DESCENT_WITHIN_IDEAL_FRACTION="$MIN_DESCENT_WITHIN_IDEAL_FRACTION" \
AUTO_AIM_DIAG_POST_AUTO_OBSERVATION_SEC="$POST_AUTO_OBSERVATION_SEC" \
AUTO_AIM_AUTO_NAME="$AUTO_AIM_AUTO_NAME" \
./gradlew "${GRADLE_ARGS[@]}" || GRADLE_EXIT=$?

SUMMARY_FILE="$(ls -1t "$OUT_DIR"/auto_aim_summary_*.txt 2>/dev/null | head -n 1 || true)"
if [[ -z "$SUMMARY_FILE" ]]; then
  SUMMARY_FILE="$(ls -1t "$OUT_DIR"/along_alliance_moving_shot_summary_*.txt 2>/dev/null | head -n 1 || true)"
fi
LATEST_WPILOG="$(ls -1t "$OUT_DIR"/*.wpilog 2>/dev/null | head -n 1 || true)"

echo ""
if [[ -n "$SUMMARY_FILE" ]]; then
  echo "Diagnostics summary:"
  cat "$SUMMARY_FILE"
else
  echo "No diagnostics summary file found in $OUT_DIR" >&2
fi

if [[ -n "$LATEST_WPILOG" ]]; then
  echo ""
  echo "Latest AKit log: $LATEST_WPILOG"
fi

exit "$GRADLE_EXIT"
